version: "3.8"

services:
  api:
    build: .
    container_name: api-orders
    restart: always
    ports:
      - "21401:21401"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://mongo:27017/test/orders"
      RABBITMQ_URL: "amqp://rabbitmq"
    networks:
      - app_network

  mongo:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

 

networks:
  app_network:
    driver: bridge
